package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"slices"
	"text/tabwriter"

	"github.com/somaz94/helm-chart-kit/internal/chart"
	"github.com/somaz94/helm-chart-kit/internal/scaffold"
	"github.com/spf13/cobra"
)

func newSyncCmd() *cobra.Command {
	var opts struct {
		chartDir string
		check    bool
		write    bool
		all      bool
		format   string
	}

	cmd := &cobra.Command{
		Use:   "sync [resource...]",
		Short: "Compare a chart's templates against what hck generates now",
		Long: `Report which of a chart's generated files differ from what this hck would
write for them today — the resource templates, and the skeleton files hck
owns outright: _helpers.tpl, NOTES.txt, .helmignore and ci/install-values.yaml.

Chart.yaml and values.yaml are deliberately not compared. The first is yours
to maintain and the second is only ever appended to, so regenerating either
would report drift that is not drift.

What it cannot tell you is why. A template you edited and a template hck
improved in a later version look identical from here — both are simply not
what hck generates now. That is why the default is a report and why --write
takes names: the answer to "should this file change?" belongs to whoever
edited it.

    hck sync                  # what differs
    hck sync --check          # the same, and non-zero if anything does
    hck sync --write ingress  # take hck's version of these
    hck sync --write --all    # take hck's version of everything

--write overwrites. Read the diff first; a chart under version control makes
that easy and one without it makes this unrecoverable.`,
		Args:              cobra.ArbitraryArgs,
		ValidArgsFunction: completeChartDrift,
		Example: `  hck sync
  hck sync --check
  hck sync --write deployment service
  hck sync --write --all --chart ./charts/payments-api`,
		RunE: func(cmd *cobra.Command, args []string) error {
			if opts.check && opts.write {
				return fmt.Errorf("--check reports and --write changes; pick one")
			}
			names := splitList(args)
			if opts.write && len(names) == 0 && !opts.all {
				return fmt.Errorf("--write overwrites, so name the resources to take, or pass --all")
			}
			if opts.all && len(names) > 0 {
				return fmt.Errorf("--all takes every drifted resource; naming some as well says two different things")
			}

			dir, err := chart.Find(opts.chartDir)
			if err != nil {
				return err
			}
			c, err := chart.Load(dir)
			if err != nil {
				return err
			}
			drifts, err := scaffold.DriftOfChart(c)
			if err != nil {
				return err
			}
			byName := map[string]scaffold.Drift{}
			for _, d := range drifts {
				byName[d.Resource] = d
			}
			for _, name := range names {
				if _, ok := byName[name]; !ok {
					return fmt.Errorf("%s does not carry %s", c.Meta.Name, name)
				}
			}

			out := cmd.OutOrStdout()
			p := newPainter(out)

			if opts.write {
				wrote := 0
				for _, d := range drifts {
					if !opts.all && !slices.Contains(names, d.Resource) {
						continue
					}
					if d.State == scaffold.Current {
						continue
					}
					if d.State == scaffold.Unreadable {
						return d.Err
					}
					if err := scaffold.WriteTemplate(c, d); err != nil {
						return err
					}
					// A file that was gone is put back, not changed, and the
					// two are worth telling apart at a glance.
					mark := p.yellow("~")
					if d.State == scaffold.Missing {
						mark = p.green("+")
					}
					fprintf(out, "  %s  %s\n", mark, d.Path)
					wrote++
				}
				if wrote == 0 {
					fprintf(out, "%s nothing to take — every named file is already what hck writes\n", p.dim("·"))
					return nil
				}
				fprintf(out, "\n%s %s\n", p.bold("updated"), c.Meta.Name)
				fprintf(out, "\nNext:\n  hck check --chart %s\n", shellQuote(c.Dir))
				return nil
			}

			if opts.format == formatJSON {
				return printSyncJSON(out, c.Meta.Name, drifts, opts.check)
			}

			fprintf(out, "%s %s\n\n", p.bold("sync"), c.Meta.Name)
			w := tabwriter.NewWriter(out, 0, 0, 2, ' ', 0)
			for _, d := range drifts {
				mark, note := p.green("="), p.dim("current")
				switch d.State {
				case scaffold.Edited:
					mark, note = p.yellow("~"), p.yellow("differs from what hck generates")
				case scaffold.Missing:
					mark, note = p.red("!"), p.red("generated by hck and no longer here")
				case scaffold.Unreadable:
					mark, note = p.red("!"), p.red(d.Err.Error())
				}
				fmt.Fprintf(w, "  %s %s\t%s\n", mark, d.Path, note)
			}
			_ = w.Flush()

			if !scaffold.AnyDrifted(drifts) {
				fprintf(out, "\n  %s every generated file is what hck writes\n", p.green("ok"))
				return nil
			}
			fprintf(out, "\n  %s\n", p.dim("hck cannot tell a local edit from an hck template that moved on."))
			fprintf(out, "  %s\n", p.dim("Read the difference before taking hck's version:"))
			fprintf(out, "    hck sync --write %s\n", firstDrifted(drifts))
			if opts.check {
				return fmt.Errorf("chart differs from what hck generates")
			}
			return nil
		},
	}

	cmd.Flags().StringVar(&opts.chartDir, "chart", ".", "chart directory; parent directories are searched for Chart.yaml")
	cmd.Flags().BoolVar(&opts.check, "check", false, "exit non-zero when anything differs")
	cmd.Flags().BoolVar(&opts.write, "write", false, "overwrite the named templates with what hck generates")
	cmd.Flags().BoolVar(&opts.all, "all", false, "with --write, take every drifted template")
	cmd.Flags().StringVar(&opts.format, "format", formatText, "output format: "+formatText+" or "+formatJSON+" (report only)")
	return cmd
}

// firstDrifted names something the hint can actually be run on, rather than a
// placeholder the reader has to translate.
func firstDrifted(drifts []scaffold.Drift) string {
	for _, d := range drifts {
		if d.State != scaffold.Current {
			return d.Resource
		}
	}
	return "<resource>"
}

// completeChartDrift offers what this chart actually has to compare, which is
// the only list on which "hck sync --write <TAB>" means anything.
func completeChartDrift(cmd *cobra.Command, _ []string, _ string) ([]string, cobra.ShellCompDirective) {
	c, err := chartFromFlag(cmd)
	if err != nil {
		return nil, cobra.ShellCompDirectiveNoFileComp
	}
	drifts, err := scaffold.DriftOfChart(c)
	if err != nil {
		return nil, cobra.ShellCompDirectiveNoFileComp
	}
	out := make([]string, 0, len(drifts))
	for _, d := range drifts {
		out = append(out, d.Resource)
	}
	return out, cobra.ShellCompDirectiveNoFileComp
}

// chartFromFlag loads the chart a command is pointed at, for completion. Any
// failure is silent: a shell completing a path that is not a chart yet should
// offer nothing, not an error.
func chartFromFlag(cmd *cobra.Command) (*chart.Chart, error) {
	dir := cmd.Flag("chart").Value.String()
	found, err := chart.Find(dir)
	if err != nil {
		return nil, err
	}
	return chart.Load(found)
}

// jsonSync is the machine-readable shape of a sync report. The field names are
// part of the interface, the same way check's are.
//
// It exists because the question this report answers — which files were
// compared, and how each came out — is one an exit status cannot carry, and
// the text report answers it with a "=", "~" or "!" in a column. A CI step
// asserting on that is coupled to the layout; this is the answer to that.
type jsonSync struct {
	Chart string `json:"chart"`
	// Files is every file that was compared, in the order the report prints
	// them. A file hck does not own is absent rather than listed as current:
	// Chart.yaml and values.yaml are never compared, and saying "current"
	// about them would be a claim nobody checked.
	Files []jsonSyncFile `json:"files"`
	// OK is true when nothing differs, and matches the exit status --check
	// produces.
	OK bool `json:"ok"`
}

type jsonSyncFile struct {
	// Resource is the catalog name, or the path again for a skeleton file.
	Resource string `json:"resource"`
	Path     string `json:"path"`
	// State is current, edited, missing or unreadable. "edited" does not mean
	// somebody edited it — hck cannot tell that from its own template having
	// moved on, which is the whole reason --write takes names.
	State string `json:"state"`
	// Skeleton marks a chart-skeleton file rather than a resource template.
	Skeleton bool `json:"skeleton"`
	// Error explains an unreadable file, and is absent otherwise.
	Error string `json:"error,omitempty"`
}

// printSyncJSON writes the report as JSON and returns the same failure the
// text path would under --check.
func printSyncJSON(out io.Writer, chartName string, drifts []scaffold.Drift, strict bool) error {
	doc := jsonSync{
		Chart: chartName,
		Files: make([]jsonSyncFile, 0, len(drifts)),
		OK:    !scaffold.AnyDrifted(drifts),
	}
	for _, d := range drifts {
		f := jsonSyncFile{
			Resource: d.Resource,
			Path:     d.Path,
			State:    string(d.State),
			Skeleton: d.Skeleton,
		}
		if d.Err != nil {
			f.Error = d.Err.Error()
		}
		doc.Files = append(doc.Files, f)
	}
	enc := json.NewEncoder(out)
	enc.SetIndent("", "  ")
	if err := enc.Encode(doc); err != nil {
		return err
	}
	if strict && !doc.OK {
		return fmt.Errorf("chart differs from what hck generates")
	}
	return nil
}
